version: '3.8'

services:
  frontend:
    build:
      context: ./page
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
      
  backend:
    build:
      context: ./auth-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"